package numbers_api

var TestData = []Number{
	{
		Text:   "45000000 is the number of turkeys Americans eat at Thanksgiving annually.",
		Number: "45000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5300 is the number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection.",
		Number: "5300",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+40 is the Eddington–Dirac number.",
		Number: "1e+40",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "60 is the years of marriage until the diamond wedding anniversary.",
		Number: "60",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "235 is the atomic mass number of an important isotope of the element uranium, the fissile isotope which is used as the fuel for nuclear reactors and in some nuclear weapons.",
		Number: "235",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "360000 is the number of words definitions in the New Oxford Dictionary of English.",
		Number: "360000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "104 is the atomic number of rutherfordium.",
		Number: "104",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "123 is the telephone number of the speaking clock for the correct time in the United Kingdom.",
		Number: "123",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "175 is the atomic number of an element temporarily called Unseptpentium.",
		Number: "175",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "714 is the number of home runs Babe Ruth scored in his career.",
		Number: "714",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "384 is the digest length of the secure hash function SHA-384 (384 is a low power of 2).",
		Number: "384",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1979 is a song by American alternative rock band The Smashing Pumpkins.",
		Number: "1979",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "8e+60 is the number of Planck time intervals since the Big Bang.",
		Number: "8e+60",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "304 is the record number of wickets taken in English cricket season by Tich Freeman in 1928.",
		Number: "304",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "141 is the number of participants (90 Indians and 51 Pilgrims) at the First Thanksgiving.",
		Number: "141",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "366 is the number of days in a leap year.",
		Number: "366",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "154 is the period in days that the sun follows on gamma-ray flares.",
		Number: "154",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "100000000000 is the number of neurons in the human brain.",
		Number: "100000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5000 is the number of base pairs in the DNA of the simplest viruses.",
		Number: "5000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1000000000000 is the number of bacteria on the surface of the human body.",
		Number: "1000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+63 is the estimate by Archimedes in The Sand Reckoner of the total number of grains of sand that could fit into the entire cosmos.",
		Number: "1e+63",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "248 is the number of organs in the human body as traditionally depicted.",
		Number: "248",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "77 is the atomic number of iridium.",
		Number: "77",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "3825000 is the number of entries on Wikipedia in the English language.",
		Number: "3825000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "141 is the number of participants (90 Indians and 51 Pilgrims) at the First Thanksgiving.",
		Number: "141",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "404 is the HTTP status code for \"Not found\", perhaps the most famous HTTP status code.",
		Number: "404",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "328 is the weight in pounds of an ovarian cyst removed from a woman in Galveston, Texas, in 1905, a world record.",
		Number: "328",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "30 is the number of days in the months April, June, September and November (and in unusual circumstances February).",
		Number: "30",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "214 is the SMTP status code for help message.",
		Number: "214",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "90000 is the average number of hairs that redheads have.",
		Number: "90000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "300 is the number of different beverages the Coca Cola company offers.",
		Number: "300",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "490 is the number of Pokémon available as of the release of Pokémon Diamond and Pearl (excluding event Pokémon).",
		Number: "490",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "179 is the rank of the Anthology 1961-1977 (1992) by Curtis Mayfield and The Impressions on Rolling Stone magazine's list of the 500 greatest albums of all time.",
		Number: "179",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "198 is the rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine's list of The 500 Greatest Songs of All Time.",
		Number: "198",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5000 is the number of base pairs in the DNA of the simplest viruses.",
		Number: "5000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "51 is the atomic number of antimony.",
		Number: "51",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1362310155 is the total number of items of mail that went through the Canadian postal system in 1950.",
		Number: "1362310155",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "276 is the highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min.",
		Number: "276",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "23 is the number of times Julius Caesar was stabbed.",
		Number: "23",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "31 is the number of flavors of Baskin-Robbins ice cream.",
		Number: "31",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "352 is the number of international appearances by Kristine Lilly for the USA women's national soccer team, an all-time record.",
		Number: "352",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "104 is the number of Corinthian columns in the Temple of Olympian Zeus, the largest temple ever built in Greece.",
		Number: "104",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "4 is the number of movements in a symphony.",
		Number: "4",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "103 is the atomic number of lawrencium, an actinide.",
		Number: "103",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "14500 is the number of unique English words occur in the King James Version of the Bible.",
		Number: "14500",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "15 is the number of checkers each side has at the start of a backgammon game.",
		Number: "15",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "83 is the atomic number of bismuth.",
		Number: "83",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "102 is the atomic number of nobelium, an actinide.",
		Number: "102",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "38 is the number of years it took the Israelites to travel from Kadesh Barnea to the Zered valley in Deuteronomy.",
		Number: "38",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "65 is the traditional age for retirement in the United Kingdom, Germany and other countries.",
		Number: "65",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "231 is the number of cubic inches in a U.S. liquid gallon.",
		Number: "231",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "172 is the number that appears on the back of the US $5 dollar bill (in the bushes at the base of the Lincoln Memorial).",
		Number: "172",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "2600 is the length of brink in feet of the Canadian \"Horseshoe\" Falls located in Niagara Falls, Ontario.",
		Number: "2600",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "115 is the atomic number of an element temporarily called ununpentium.",
		Number: "115",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "221 is the house number on Baker Street of the fictional London residence of Sherlock Holmes.",
		Number: "221",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "125000 is the number of average strands of hair in the human head.",
		Number: "125000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "6.28e+57 is the number of keys in the AES 192 bit key space (symmetric cipher).",
		Number: "6.28e+57",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "78 is the atomic number of platinum.",
		Number: "78",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "29 is the number of attributes existing according to The Strokes in You Only Live Once.",
		Number: "29",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "214 is the first area code of metropolitan Dallas, Texas.",
		Number: "214",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1500 is the approximate number of peanut butter sandwiches the average American kid will eat by high school graduation.",
		Number: "1500",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "10000 is the gallons of saliva an average human produces in a lifetime.",
		Number: "10000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "60000000000000000000 is the permutations of a 10-character password on a 95-character set found on standard computer keyboards.",
		Number: "60000000000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "98 is the temperature (F) of the normal body.",
		Number: "98",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "352 is the number of international appearances by Kristine Lilly for the USA women's national soccer team, an all-time record.",
		Number: "352",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "25 is the minimum age of candidates for election to the United States House of Representatives.",
		Number: "25",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "171 is the atomic number of an element called Ununseptunium.",
		Number: "171",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "26 is the number of letters in the English and Interlingua alphabets.",
		Number: "26",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "61000 is the average number of people airborne over the US at any given hour.",
		Number: "61000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "27 is the current number of Amendments to the United States Constitution (2012 February).",
		Number: "27",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "69 is the atomic number of thulium, a lanthanide.",
		Number: "69",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "98 is the temperature (F) of the normal body.",
		Number: "98",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "16 is the minimum age that one can drop out of school in most states of the US (however, restrictions apply and vary depending on state).",
		Number: "16",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "190 is the length in minutes of the Right Stuff.",
		Number: "190",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "78 is the number of lines that make up Metatron's Cube.",
		Number: "78",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "161 is the the number of theatrical shorts of Tom and Jerry cartoons between 1940 and 1967.",
		Number: "161",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "177 is the atomic number of an element temporarily called Unseptseptium.",
		Number: "177",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "720 is the number of degrees in two circles (= 2 × 360).",
		Number: "720",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "695 is the number of people dead in the single deadliest tornado in United States history (the F5 Tri-State Tornado in 1925).",
		Number: "695",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "198 is the rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine's list of The 500 Greatest Songs of All Time.",
		Number: "198",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "115 is the atomic number of an element temporarily called ununpentium.",
		Number: "115",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "562 is the number of Native American (including Alaskan) Nations, or \"Tribes,\" recognized by the USA government.",
		Number: "562",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5880000 is the number of geographic features named by the NIMA GEOnet Names Server.",
		Number: "5880000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "72 is the average number of heartbeats per minute for a resting adult.",
		Number: "72",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "712 is the largest known number such that it and its 8th power have no common digits.",
		Number: "712",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "64374 is the number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean).",
		Number: "64374",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "47 is the number of El-Aurians Scotty manages to beam up before their ship is destroyed by the energy ribbon.",
		Number: "47",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "189 is the rank of Brazil in population density.",
		Number: "189",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "152 is the number of diapers solder in a Pampers Swaddlers pack.",
		Number: "152",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "184 is the distance in light years to Eta Aquarii,a star in the constellation Aquarius.",
		Number: "184",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "27 is the number of bones in the human hand.",
		Number: "27",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "714 is the number of home runs Babe Ruth scored in his career.",
		Number: "714",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "9 is the number of circles of Hell in Dante's Divine Comedy.",
		Number: "9",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "9220000000000000000 is the largest number which can fit into a signed (two's complement) 64-bit integer on a computer.",
		Number: "9220000000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "7e+27 is the number of atoms in the average human body.",
		Number: "7e+27",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "755 is the number of home runs Hank Aaron ended his career with in 1976, a Major League record at the time.",
		Number: "755",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "64 is number of golden disks in the myth of the Tower of Hanoi.",
		Number: "64",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "125000 is the number of average strands of hair in the human head.",
		Number: "125000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "183 is the rank of Laos in countries by population density.",
		Number: "183",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1728 is braces were first invented by Pierre Fauchard.",
		Number: "1728",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "194 is the rank of Isle of Man in world population.",
		Number: "194",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5 is times Muslims pray to Allah a day.",
		Number: "5",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "280000000000000 is the number of possible unique physical addresses.",
		Number: "280000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "149000000 is the number of kilometres from the Earth the sun is.",
		Number: "149000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "695 is the number of people dead in the single deadliest tornado in United States history (the F5 Tri-State Tornado in 1925).",
		Number: "695",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "693 is the number of sections in Ludwig Wittgenstein's Philosophical Investigations.",
		Number: "693",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "396 is the displacement in cubic inches of early Chevrolet Big-Block engines.",
		Number: "396",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "67 is the highest two-digit odd number not presently designating any highway in the Interstate Highway System of the United States.",
		Number: "67",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "525998433 is the number of distinct websites as of November 2011.",
		Number: "525998433",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5300 is the number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection.",
		Number: "5300",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "749 is the pounds of paper products used by an American individual annually on average.",
		Number: "749",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "17000 is the length in km of bicycle lanes with special bicycle traffic lights in the Netherlands.",
		Number: "17000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "76 is the atomic number of osmium.",
		Number: "76",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "30000 is the number of distinct Chinese characters.",
		Number: "30000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1700 is the weight in pounds that the Kodiak bear can grow up to, a native of Alaska and one of the largest bears.",
		Number: "1700",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "555 is the number of keyboard sonatas written by Domenico Scarlatti, according to the catalog by Ralph Kirkpatrick.",
		Number: "555",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "432 is three-dozen sets of a dozen, making it three gross.",
		Number: "432",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "71 is the number of different characters that can be used with a standard English Keyboard, excluding uppercase letters.",
		Number: "71",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "152 is the number of diapers solder in a Pampers Swaddlers pack.",
		Number: "152",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "361 is the number of positions on a standard 19 x 19 Go board.",
		Number: "361",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "276 is the highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min.",
		Number: "276",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "52 is the number of letters in the English alphabet, if majuscules are distinguished from minuscules.",
		Number: "52",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "99 is a common price ending in psychological pricing.",
		Number: "99",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "68 is the ideal temperature (F) for developing black-and-white film.",
		Number: "68",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+36 is the ratio of the electromagnetic to the gravitational forces between two protons.",
		Number: "1e+36",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "126 is the number of years that Gilgamesh reigned according to the Sumerian king list.",
		Number: "126",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "201 is the HTTP status code indicating a new resource was successfully created in response to the request.",
		Number: "201",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "400000000000 is the number of stars in the Milky Way galaxy.",
		Number: "400000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "240 is distinct solutions of the Soma cube puzzle.",
		Number: "240",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "Infinity is the largest value that can be represented in the IEEE double precision floating-point format.",
		Number: "null",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "2147483647 is the largest number which can fit into a signed (two's complement) 32-bit integer on a computer.",
		Number: "2147483647",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1000 is the number of words a picture is worth.",
		Number: "1000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "207 is the area code for the US state of Maine.",
		Number: "207",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "81 is the number of prayers said in the Rosary in each night.",
		Number: "81",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "58000000 is the number of customers McDonald restaurants serve food and drink to on a daily basis in 2011.",
		Number: "58000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "13 is the number of Oscar nominations of actress Meryl Streep, who holds the record for the most Oscar nominated actress.",
		Number: "13",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "172 is the atomic number of an element temporarily called Unseptbium.",
		Number: "172",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "154 is the period in days that the sun follows on gamma-ray flares.",
		Number: "154",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "61000 is the average number of people airborne over the US at any given hour.",
		Number: "61000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "230 is the common voltage in the European Union.",
		Number: "230",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "614 is the number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613.",
		Number: "614",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "432 is three-dozen sets of a dozen, making it three gross.",
		Number: "432",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "9 is the number of circles of Hell in Dante's Divine Comedy.",
		Number: "9",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "714 is the number of home runs Babe Ruth scored in his career.",
		Number: "714",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "179 is the rank of Estonia in world population density.",
		Number: "179",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "240 is distinct solutions of the Soma cube puzzle.",
		Number: "240",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+120 is the Shannon number, an estimation of the game-tree complexity of chess.",
		Number: "1e+120",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+150 is the estimation of the game-tree complexity of xiangqi.",
		Number: "1e+150",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "58 is the minimum wind speed (mph) needed to issue a Severe Thunderstorm Warning.",
		Number: "58",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "16 is the number of personality types in the Myers-Briggs classification system.",
		Number: "16",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "4200000 is the number of couples in the United States that live together but are not married.",
		Number: "4200000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "390 is the speed in feet per second that nerve impulses for muscle position travel at.",
		Number: "390",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "2 is the lowest channel of television in the United States, Canada, Argentina and Mexico on which television signals are broadcast.",
		Number: "2",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "16777216 is the number of different colors that can be generated using the hex code system in HTML.",
		Number: "16777216",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "133 is the number of career touchdowns from 1983 - 1996 of Canadian Football League quarterback Danny Barrett.",
		Number: "133",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "280000000000000 is the number of possible unique physical addresses.",
		Number: "280000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "192 is the distance in feet the Hampstead London Underground station is below ground level.",
		Number: "192",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "186 is the length of the Judgment at Nuremberg measured in 186 minutes.",
		Number: "186",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "172 is the atomic number of an element temporarily called Unseptbium.",
		Number: "172",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "2055001 is the number of people employed by Wal-mart in 2007.",
		Number: "2055001",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1982 is the average price for a major league baseball game ticket in 2004 in cents.",
		Number: "1982",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "64374 is the number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean).",
		Number: "64374",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5e+30 is the number of bacterial cells on Earth.",
		Number: "5e+30",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "270 is the average number of days in human pregnancy.",
		Number: "270",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "171 is the record number of goals scored by France at the 1998 World Cup.",
		Number: "171",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "153 is the frequency in kHz of of the longwave transmitters Donebach, Ingøy, Braşov, and Kenadsa.",
		Number: "153",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "96 is the rating of Skyrim on metacritic.com.",
		Number: "96",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "93 is the atomic number of neptunium.",
		Number: "93",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "267000 is the number of words in James Joyce's Ulysses.",
		Number: "267000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "145 is the atomic number of Unquadpentium.",
		Number: "145",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "129 is the combined 2-year total of home runs for baseball's Sammy Sosa with 66 home runs in 1999 and 63 in 2000.",
		Number: "129",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "145 is the atomic number of Unquadpentium.",
		Number: "145",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "7 is the number of main islands of mythological Atlantis.",
		Number: "7",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "144 is the number of months in 12 years.",
		Number: "144",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1e+40 is the Eddington–Dirac number.",
		Number: "1e+40",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "22000 is the approximate number of workers who died during the building of the Panama Canal due to accidents and diseases.",
		Number: "22000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "712 is the largest known number such that it and its 8th power have no common digits.",
		Number: "712",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "137 is a radioactive isotope of Caesium formed by nuclear fission.",
		Number: "137",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "157 is the elevation in meters of Atalanti Island in the North Euboean Gulf of the Aegean Sea.",
		Number: "157",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "75 is the age limit for Canadian senators.",
		Number: "75",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "1300 is the number of babies born prematurely in the USA every day.",
		Number: "1300",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "10000000000 is the number of times the original Pac Man has been played as estimated by Namco, the manufacturers of Pac Man.",
		Number: "10000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "45000000 is the number of turkeys Americans eat at Thanksgiving annually.",
		Number: "45000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "930000 is the number of words in the King James Version of the Bible.",
		Number: "930000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "626 is the number of compositions of Wolfgang Amadeus Mozart, according to the Köchel Catalogue.",
		Number: "626",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "145 is the atomic number of Unquadpentium.",
		Number: "145",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "175 is the number of weeks that professional golfer David Toms spent in the top-10 of the Official World Golf Rankings between 2001 and 2006.",
		Number: "175",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "587 is the outgoing port for email message submission.",
		Number: "587",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "17 is the minimum driving age for a car or van in the United Kingdom.",
		Number: "17",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "10 is the number of spacetime dimensions in some superstring theories.",
		Number: "10",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "90000 is the average number of hairs that redheads have.",
		Number: "90000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "116 is the prefix for several EU-wide telephone helplines designated as harmonised service of social value.",
		Number: "116",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "155 is the number of episodes the TV series Sea Hunt ran in syndication from 1958 to 1961.",
		Number: "155",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "270 is the average number of days in human pregnancy.",
		Number: "270",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "137 is the California Penal Code for \"Offer bribe to influence testimony\".",
		Number: "137",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "93 is that approximate distance in millions of miles the Sun is away from the Earth.",
		Number: "93",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "30000 is the number of distinct Chinese characters.",
		Number: "30000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "5500000000000000 is the number of estimated ants on Earth alive at any one time.",
		Number: "5500000000000000",
		Found:  true,
		Type:   "trivia",
	},
	{
		Text:   "103 is the atomic number of lawrencium, an actinide.",
		Number: "103",
		Found:  true,
		Type:   "trivia",
	},
}
