USE triviadb;
INSERT INTO numbers(text,number,found,type) VALUES ('45000000 is the number of turkeys Americans eat at Thanksgiving annually.','45000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5300 is the number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection.','5300',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+40 is the Eddington–Dirac number.','1e+40',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('60 is the years of marriage until the diamond wedding anniversary.','60',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('235 is the atomic mass number of an important isotope of the element uranium, the fissile isotope which is used as the fuel for nuclear reactors and in some nuclear weapons.','235',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('360000 is the number of words definitions in the New Oxford Dictionary of English.','360000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('104 is the atomic number of rutherfordium.','104',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('123 is the telephone number of the speaking clock for the correct time in the United Kingdom.','123',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('175 is the atomic number of an element temporarily called Unseptpentium.','175',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('714 is the number of home runs Babe Ruth scored in his career.','714',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('384 is the digest length of the secure hash function SHA-384 (384 is a low power of 2).','384',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1979 is a song by American alternative rock band The Smashing Pumpkins.','1979',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('8e+60 is the number of Planck time intervals since the Big Bang.','8e+60',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('304 is the record number of wickets taken in English cricket season by Tich Freeman in 1928.','304',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('141 is the number of participants (90 Indians and 51 Pilgrims) at the First Thanksgiving.','141',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('366 is the number of days in a leap year.','366',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('154 is the period in days that the sun follows on gamma-ray flares.','154',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('100000000000 is the number of neurons in the human brain.','100000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5000 is the number of base pairs in the DNA of the simplest viruses.','5000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1000000000000 is the number of bacteria on the surface of the human body.','1000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+63 is the estimate by Archimedes in The Sand Reckoner of the total number of grains of sand that could fit into the entire cosmos.','1e+63',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('248 is the number of organs in the human body as traditionally depicted.','248',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('77 is the atomic number of iridium.','77',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('3825000 is the number of entries on Wikipedia in the English language.','3825000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('141 is the number of participants (90 Indians and 51 Pilgrims) at the First Thanksgiving.','141',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('404 is the HTTP status code for "Not found", perhaps the most famous HTTP status code.','404',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('328 is the weight in pounds of an ovarian cyst removed from a woman in Galveston, Texas, in 1905, a world record.','328',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('30 is the number of days in the months April, June, September and November (and in unusual circumstances February).','30',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('214 is the SMTP status code for help message.','214',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('90000 is the average number of hairs that redheads have.','90000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('300 is the number of different beverages the Coca Cola company offers.','300',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('490 is the number of Pokémon available as of the release of Pokémon Diamond and Pearl (excluding event Pokémon).','490',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('179 is the rank of the Anthology 1961-1977 (1992) by Curtis Mayfield and The Impressions on Rolling Stone magazine''s list of the 500 greatest albums of all time.','179',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('198 is the rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine''s list of The 500 Greatest Songs of All Time.','198',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5000 is the number of base pairs in the DNA of the simplest viruses.','5000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('51 is the atomic number of antimony.','51',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1362310155 is the total number of items of mail that went through the Canadian postal system in 1950.','1362310155',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('276 is the highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min.','276',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('23 is the number of times Julius Caesar was stabbed.','23',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('31 is the number of flavors of Baskin-Robbins ice cream.','31',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('352 is the number of international appearances by Kristine Lilly for the USA women''s national soccer team, an all-time record.','352',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('104 is the number of Corinthian columns in the Temple of Olympian Zeus, the largest temple ever built in Greece.','104',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('4 is the number of movements in a symphony.','4',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('103 is the atomic number of lawrencium, an actinide.','103',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('14500 is the number of unique English words occur in the King James Version of the Bible.','14500',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('15 is the number of checkers each side has at the start of a backgammon game.','15',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('83 is the atomic number of bismuth.','83',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('102 is the atomic number of nobelium, an actinide.','102',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('38 is the number of years it took the Israelites to travel from Kadesh Barnea to the Zered valley in Deuteronomy.','38',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('65 is the traditional age for retirement in the United Kingdom, Germany and other countries.','65',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('231 is the number of cubic inches in a U.S. liquid gallon.','231',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('172 is the number that appears on the back of the US $5 dollar bill (in the bushes at the base of the Lincoln Memorial).','172',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('2600 is the length of brink in feet of the Canadian "Horseshoe" Falls located in Niagara Falls, Ontario.','2600',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('115 is the atomic number of an element temporarily called ununpentium.','115',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('221 is the house number on Baker Street of the fictional London residence of Sherlock Holmes.','221',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('125000 is the number of average strands of hair in the human head.','125000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('6.28e+57 is the number of keys in the AES 192 bit key space (symmetric cipher).','6.28e+57',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('78 is the atomic number of platinum.','78',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('29 is the number of attributes existing according to The Strokes in You Only Live Once.','29',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('214 is the first area code of metropolitan Dallas, Texas.','214',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1500 is the approximate number of peanut butter sandwiches the average American kid will eat by high school graduation.','1500',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('10000 is the gallons of saliva an average human produces in a lifetime.','10000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('60000000000000000000 is the permutations of a 10-character password on a 95-character set found on standard computer keyboards.','60000000000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('98 is the temperature (F) of the normal body.','98',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('352 is the number of international appearances by Kristine Lilly for the USA women''s national soccer team, an all-time record.','352',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('25 is the minimum age of candidates for election to the United States House of Representatives.','25',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('171 is the atomic number of an element called Ununseptunium.','171',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('26 is the number of letters in the English and Interlingua alphabets.','26',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('61000 is the average number of people airborne over the US at any given hour.','61000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('27 is the current number of Amendments to the United States Constitution (2012 February).','27',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('69 is the atomic number of thulium, a lanthanide.','69',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('98 is the temperature (F) of the normal body.','98',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('16 is the minimum age that one can drop out of school in most states of the US (however, restrictions apply and vary depending on state).','16',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('190 is the length in minutes of the Right Stuff.','190',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('78 is the number of lines that make up Metatron''s Cube.','78',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('161 is the the number of theatrical shorts of Tom and Jerry cartoons between 1940 and 1967.','161',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('177 is the atomic number of an element temporarily called Unseptseptium.','177',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('720 is the number of degrees in two circles (= 2 × 360).','720',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('695 is the number of people dead in the single deadliest tornado in United States history (the F5 Tri-State Tornado in 1925).','695',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('198 is the rank of Hey Joe (1966) by Jimi Hendrix on Rolling Stone magazine''s list of The 500 Greatest Songs of All Time.','198',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('115 is the atomic number of an element temporarily called ununpentium.','115',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('562 is the number of Native American (including Alaskan) Nations, or "Tribes," recognized by the USA government.','562',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5880000 is the number of geographic features named by the NIMA GEOnet Names Server.','5880000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('72 is the average number of heartbeats per minute for a resting adult.','72',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('712 is the largest known number such that it and its 8th power have no common digits.','712',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('64374 is the number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean).','64374',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('47 is the number of El-Aurians Scotty manages to beam up before their ship is destroyed by the energy ribbon.','47',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('189 is the rank of Brazil in population density.','189',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('152 is the number of diapers solder in a Pampers Swaddlers pack.','152',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('184 is the distance in light years to Eta Aquarii,a star in the constellation Aquarius.','184',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('27 is the number of bones in the human hand.','27',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('714 is the number of home runs Babe Ruth scored in his career.','714',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('9 is the number of circles of Hell in Dante''s Divine Comedy.','9',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('9220000000000000000 is the largest number which can fit into a signed (two''s complement) 64-bit integer on a computer.','9220000000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('7e+27 is the number of atoms in the average human body.','7e+27',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('755 is the number of home runs Hank Aaron ended his career with in 1976, a Major League record at the time.','755',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('64 is number of golden disks in the myth of the Tower of Hanoi.','64',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('125000 is the number of average strands of hair in the human head.','125000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('183 is the rank of Laos in countries by population density.','183',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1728 is braces were first invented by Pierre Fauchard.','1728',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('194 is the rank of Isle of Man in world population.','194',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5 is times Muslims pray to Allah a day.','5',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('280000000000000 is the number of possible unique physical addresses.','280000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('149000000 is the number of kilometres from the Earth the sun is.','149000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('695 is the number of people dead in the single deadliest tornado in United States history (the F5 Tri-State Tornado in 1925).','695',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('693 is the number of sections in Ludwig Wittgenstein''s Philosophical Investigations.','693',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('396 is the displacement in cubic inches of early Chevrolet Big-Block engines.','396',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('67 is the highest two-digit odd number not presently designating any highway in the Interstate Highway System of the United States.','67',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('525998433 is the number of distinct websites as of November 2011.','525998433',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5300 is the number of gum wrappers that Steve Fletcher has, the record for the largest gum wrapper collection.','5300',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('749 is the pounds of paper products used by an American individual annually on average.','749',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('17000 is the length in km of bicycle lanes with special bicycle traffic lights in the Netherlands.','17000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('76 is the atomic number of osmium.','76',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('30000 is the number of distinct Chinese characters.','30000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1700 is the weight in pounds that the Kodiak bear can grow up to, a native of Alaska and one of the largest bears.','1700',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('555 is the number of keyboard sonatas written by Domenico Scarlatti, according to the catalog by Ralph Kirkpatrick.','555',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('432 is three-dozen sets of a dozen, making it three gross.','432',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('71 is the number of different characters that can be used with a standard English Keyboard, excluding uppercase letters.','71',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('152 is the number of diapers solder in a Pampers Swaddlers pack.','152',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('361 is the number of positions on a standard 19 x 19 Go board.','361',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('276 is the highest number of rounds in boxing history, in a bare-knuckle fight in 1825 that saw Jack Jones beat Patsy Tunney after 4hr 30min.','276',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('52 is the number of letters in the English alphabet, if majuscules are distinguished from minuscules.','52',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('99 is a common price ending in psychological pricing.','99',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('68 is the ideal temperature (F) for developing black-and-white film.','68',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+36 is the ratio of the electromagnetic to the gravitational forces between two protons.','1e+36',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('126 is the number of years that Gilgamesh reigned according to the Sumerian king list.','126',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('201 is the HTTP status code indicating a new resource was successfully created in response to the request.','201',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('400000000000 is the number of stars in the Milky Way galaxy.','400000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('240 is distinct solutions of the Soma cube puzzle.','240',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('Infinity is the largest value that can be represented in the IEEE double precision floating-point format.','NULL',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('2147483647 is the largest number which can fit into a signed (two''s complement) 32-bit integer on a computer.','2147483647',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1000 is the number of words a picture is worth.','1000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('207 is the area code for the US state of Maine.','207',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('81 is the number of prayers said in the Rosary in each night.','81',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('58000000 is the number of customers McDonald restaurants serve food and drink to on a daily basis in 2011.','58000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('13 is the number of Oscar nominations of actress Meryl Streep, who holds the record for the most Oscar nominated actress.','13',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('172 is the atomic number of an element temporarily called Unseptbium.','172',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('154 is the period in days that the sun follows on gamma-ray flares.','154',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('61000 is the average number of people airborne over the US at any given hour.','61000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('230 is the common voltage in the European Union.','230',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('614 is the number of Commandments, according to Rabbi Fackenheimin, that should be in Judaism, vs. the traditional 613.','614',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('432 is three-dozen sets of a dozen, making it three gross.','432',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('9 is the number of circles of Hell in Dante''s Divine Comedy.','9',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('714 is the number of home runs Babe Ruth scored in his career.','714',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('179 is the rank of Estonia in world population density.','179',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('240 is distinct solutions of the Soma cube puzzle.','240',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+120 is the Shannon number, an estimation of the game-tree complexity of chess.','1e+120',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+150 is the estimation of the game-tree complexity of xiangqi.','1e+150',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('58 is the minimum wind speed (mph) needed to issue a Severe Thunderstorm Warning.','58',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('16 is the number of personality types in the Myers-Briggs classification system.','16',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('4200000 is the number of couples in the United States that live together but are not married.','4200000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('390 is the speed in feet per second that nerve impulses for muscle position travel at.','390',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('2 is the lowest channel of television in the United States, Canada, Argentina and Mexico on which television signals are broadcast.','2',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('16777216 is the number of different colors that can be generated using the hex code system in HTML.','16777216',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('133 is the number of career touchdowns from 1983 - 1996 of Canadian Football League quarterback Danny Barrett.','133',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('280000000000000 is the number of possible unique physical addresses.','280000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('192 is the distance in feet the Hampstead London Underground station is below ground level.','192',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('186 is the length of the Judgment at Nuremberg measured in 186 minutes.','186',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('172 is the atomic number of an element temporarily called Unseptbium.','172',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('2055001 is the number of people employed by Wal-mart in 2007.','2055001',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1982 is the average price for a major league baseball game ticket in 2004 in cents.','1982',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('64374 is the number of km in length the greatest mountain range extends from (Arctic Ocean to the Atlantic Ocean).','64374',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5e+30 is the number of bacterial cells on Earth.','5e+30',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('270 is the average number of days in human pregnancy.','270',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('171 is the record number of goals scored by France at the 1998 World Cup.','171',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('153 is the frequency in kHz of of the longwave transmitters Donebach, Ingøy, Braşov, and Kenadsa.','153',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('96 is the rating of Skyrim on metacritic.com.','96',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('93 is the atomic number of neptunium.','93',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('267000 is the number of words in James Joyce''s Ulysses.','267000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('145 is the atomic number of Unquadpentium.','145',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('129 is the combined 2-year total of home runs for baseball''s Sammy Sosa with 66 home runs in 1999 and 63 in 2000.','129',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('145 is the atomic number of Unquadpentium.','145',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('7 is the number of main islands of mythological Atlantis.','7',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('144 is the number of months in 12 years.','144',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1e+40 is the Eddington–Dirac number.','1e+40',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('22000 is the approximate number of workers who died during the building of the Panama Canal due to accidents and diseases.','22000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('712 is the largest known number such that it and its 8th power have no common digits.','712',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('137 is a radioactive isotope of Caesium formed by nuclear fission.','137',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('157 is the elevation in meters of Atalanti Island in the North Euboean Gulf of the Aegean Sea.','157',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('75 is the age limit for Canadian senators.','75',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('1300 is the number of babies born prematurely in the USA every day.','1300',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('10000000000 is the number of times the original Pac Man has been played as estimated by Namco, the manufacturers of Pac Man.','10000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('45000000 is the number of turkeys Americans eat at Thanksgiving annually.','45000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('930000 is the number of words in the King James Version of the Bible.','930000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('626 is the number of compositions of Wolfgang Amadeus Mozart, according to the Köchel Catalogue.','626',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('145 is the atomic number of Unquadpentium.','145',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('175 is the number of weeks that professional golfer David Toms spent in the top-10 of the Official World Golf Rankings between 2001 and 2006.','175',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('587 is the outgoing port for email message submission.','587',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('17 is the minimum driving age for a car or van in the United Kingdom.','17',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('10 is the number of spacetime dimensions in some superstring theories.','10',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('90000 is the average number of hairs that redheads have.','90000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('116 is the prefix for several EU-wide telephone helplines designated as harmonised service of social value.','116',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('155 is the number of episodes the TV series Sea Hunt ran in syndication from 1958 to 1961.','155',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('270 is the average number of days in human pregnancy.','270',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('137 is the California Penal Code for "Offer bribe to influence testimony".','137',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('93 is that approximate distance in millions of miles the Sun is away from the Earth.','93',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('30000 is the number of distinct Chinese characters.','30000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('5500000000000000 is the number of estimated ants on Earth alive at any one time.','5500000000000000',true,'trivia');
INSERT INTO numbers(text,number,found,type) VALUES ('103 is the atomic number of lawrencium, an actinide.','103',true,'trivia');
